### ISSUE TITLE
error=csrf-invalid

### ISSUE THREAD

**Issue by voogarix** [bajpangosh/nodeBB#1]
Hi. i;ve succesfully installed nodebb using your script. after that i cant log in to my website. searched on google, found some solutions, but i cant find default nodebb installation location.. i have to change config.json file but it doesnt exist on default location.

**Comment by bajpangosh** [comment]
https://www.youtube.com/watch?v=3uWEumDKoDw please follow the video tutorial,Use only on Ubuntu-18.04. and you need a cloudflare account for universal SSL.

**Comment by voogarix** [comment]
thanks for everything. did everything as on video. no time to upgrade. anyway i cant find nodebb installation folder. where is it?

**Comment by bajpangosh** [comment]
location:- 

> "/var/www/yourdomainname"
